# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plothistorywidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotHistoryWidget(object):
    def setupUi(self, PlotHistoryWidget):
        PlotHistoryWidget.setObjectName("PlotHistoryWidget")
        PlotHistoryWidget.resize(822, 307)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PlotHistoryWidget.sizePolicy().hasHeightForWidth())
        PlotHistoryWidget.setSizePolicy(sizePolicy)
        self.gridLayout = QtWidgets.QGridLayout(PlotHistoryWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.clear_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 1, 3, 1, 1)
        self.set_min_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.set_min_pushButton.setObjectName("set_min_pushButton")
        self.gridLayout.addWidget(self.set_min_pushButton, 1, 0, 1, 1)
        self.set_max_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.set_max_pushButton.setObjectName("set_max_pushButton")
        self.gridLayout.addWidget(self.set_max_pushButton, 1, 1, 1, 1)
        self.activate_checkBox = QtWidgets.QCheckBox(PlotHistoryWidget)
        self.activate_checkBox.setObjectName("activate_checkBox")
        self.gridLayout.addWidget(self.activate_checkBox, 1, 4, 1, 1)
        self.history_PlotWidget = PlotWidget(PlotHistoryWidget)
        self.history_PlotWidget.setMinimumSize(QtCore.QSize(800, 250))
        self.history_PlotWidget.setObjectName("history_PlotWidget")
        self.gridLayout.addWidget(self.history_PlotWidget, 0, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)

        self.retranslateUi(PlotHistoryWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotHistoryWidget)

    def retranslateUi(self, PlotHistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotHistoryWidget.setWindowTitle(_translate("PlotHistoryWidget", "Form"))
        self.clear_pushButton.setText(_translate("PlotHistoryWidget", "Clear History"))
        self.set_min_pushButton.setText(_translate("PlotHistoryWidget", "Set Minimum"))
        self.set_max_pushButton.setText(_translate("PlotHistoryWidget", "Set Maximum"))
        self.activate_checkBox.setText(_translate("PlotHistoryWidget", "Activate?"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotHistoryWidget = QtWidgets.QWidget()
    ui = Ui_PlotHistoryWidget()
    ui.setupUi(PlotHistoryWidget)
    PlotHistoryWidget.show()
    sys.exit(app.exec_())
