# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camerawindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraWindow(object):
    def setupUi(self, CameraWindow):
        CameraWindow.setObjectName("CameraWindow")
        CameraWindow.resize(1033, 509)
        self.centralwidget = QtWidgets.QWidget(CameraWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.view_stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.view_stackedWidget.sizePolicy().hasHeightForWidth())
        self.view_stackedWidget.setSizePolicy(sizePolicy)
        self.view_stackedWidget.setObjectName("view_stackedWidget")
        self.imageview_page = QtWidgets.QWidget()
        self.imageview_page.setObjectName("imageview_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.imageview_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.videovieweditor = ImageViewEditor(self.imageview_page)
        self.videovieweditor.setObjectName("videovieweditor")
        self.gridLayout_2.addWidget(self.videovieweditor, 0, 0, 1, 1)
        self.view_stackedWidget.addWidget(self.imageview_page)
        self.absorption_view_page = QtWidgets.QWidget()
        self.absorption_view_page.setObjectName("absorption_view_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.absorption_view_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.absorption_view_widget = AbsorptionViewWidget(self.absorption_view_page)
        self.absorption_view_widget.setObjectName("absorption_view_widget")
        self.gridLayout_3.addWidget(self.absorption_view_widget, 0, 2, 1, 1)
        self.view_stackedWidget.addWidget(self.absorption_view_page)
        self.gridLayout.addWidget(self.view_stackedWidget, 0, 0, 3, 4)
        self.roi_analyzer_frame = QtWidgets.QFrame(self.centralwidget)
        self.roi_analyzer_frame.setStyleSheet("")
        self.roi_analyzer_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.roi_analyzer_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.roi_analyzer_frame.setObjectName("roi_analyzer_frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.roi_analyzer_frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.roi_analyzer_checkBox = QtWidgets.QCheckBox(self.roi_analyzer_frame)
        self.roi_analyzer_checkBox.setObjectName("roi_analyzer_checkBox")
        self.gridLayout_4.addWidget(self.roi_analyzer_checkBox, 1, 0, 1, 1)
        self.roi_label = QtWidgets.QLabel(self.roi_analyzer_frame)
        self.roi_label.setObjectName("roi_label")
        self.gridLayout_4.addWidget(self.roi_label, 0, 0, 1, 1)
        self.roi_bg_subtract_checkBox = QtWidgets.QCheckBox(self.roi_analyzer_frame)
        self.roi_bg_subtract_checkBox.setObjectName("roi_bg_subtract_checkBox")
        self.gridLayout_4.addWidget(self.roi_bg_subtract_checkBox, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.roi_analyzer_frame, 3, 3, 1, 1)
        self.image_capture_mode_frame = QtWidgets.QFrame(self.centralwidget)
        self.image_capture_mode_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.image_capture_mode_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.image_capture_mode_frame.setObjectName("image_capture_mode_frame")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.image_capture_mode_frame)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.video_mode_radioButton = QtWidgets.QRadioButton(self.image_capture_mode_frame)
        self.video_mode_radioButton.setChecked(True)
        self.video_mode_radioButton.setObjectName("video_mode_radioButton")
        self.image_capture_buttonGroup = QtWidgets.QButtonGroup(CameraWindow)
        self.image_capture_buttonGroup.setObjectName("image_capture_buttonGroup")
        self.image_capture_buttonGroup.addButton(self.video_mode_radioButton)
        self.gridLayout_5.addWidget(self.video_mode_radioButton, 2, 0, 1, 1)
        self.image_capture_mode_label = QtWidgets.QLabel(self.image_capture_mode_frame)
        self.image_capture_mode_label.setObjectName("image_capture_mode_label")
        self.gridLayout_5.addWidget(self.image_capture_mode_label, 0, 0, 1, 1)
        self.absorption_mode_radioButton = QtWidgets.QRadioButton(self.image_capture_mode_frame)
        self.absorption_mode_radioButton.setObjectName("absorption_mode_radioButton")
        self.image_capture_buttonGroup.addButton(self.absorption_mode_radioButton)
        self.gridLayout_5.addWidget(self.absorption_mode_radioButton, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.image_capture_mode_frame, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 1, 2, 1)
        self.camera_control_widget = CameraControlWidget(self.centralwidget)
        self.camera_control_widget.setObjectName("camera_control_widget")
        self.gridLayout.addWidget(self.camera_control_widget, 3, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 4, 3, 1, 1)
        CameraWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CameraWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 26))
        self.menubar.setObjectName("menubar")
        CameraWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CameraWindow)
        self.statusbar.setObjectName("statusbar")
        CameraWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CameraWindow)
        self.view_stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CameraWindow)

    def retranslateUi(self, CameraWindow):
        _translate = QtCore.QCoreApplication.translate
        CameraWindow.setWindowTitle(_translate("CameraWindow", "jkam"))
        self.roi_analyzer_checkBox.setText(_translate("CameraWindow", "Enable"))
        self.roi_label.setText(_translate("CameraWindow", "ROI Analyzer"))
        self.roi_bg_subtract_checkBox.setText(_translate("CameraWindow", "Background Subtract"))
        self.video_mode_radioButton.setText(_translate("CameraWindow", "Video"))
        self.image_capture_mode_label.setText(_translate("CameraWindow", "Image Capture Mode"))
        self.absorption_mode_radioButton.setText(_translate("CameraWindow", "Absorption"))
from absorption_view_widget import AbsorptionViewWidget
from cameracontrolwidget import CameraControlWidget
from imagevieweditor import ImageViewEditor


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraWindow = QtWidgets.QMainWindow()
    ui = Ui_CameraWindow()
    ui.setupUi(CameraWindow)
    CameraWindow.show()
    sys.exit(app.exec_())
