# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cameracontrolwidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CameraControlWidget(object):
    def setupUi(self, CameraControlWidget):
        CameraControlWidget.setObjectName("CameraControlWidget")
        CameraControlWidget.resize(231, 260)
        self.gridLayout = QtWidgets.QGridLayout(CameraControlWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.arm_pushButton = QtWidgets.QPushButton(CameraControlWidget)
        self.arm_pushButton.setObjectName("arm_pushButton")
        self.gridLayout.addWidget(self.arm_pushButton, 0, 0, 1, 2)
        self.start_pushButton = QtWidgets.QPushButton(CameraControlWidget)
        self.start_pushButton.setEnabled(False)
        self.start_pushButton.setObjectName("start_pushButton")
        self.gridLayout.addWidget(self.start_pushButton, 1, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 11, 0, 1, 2)
        self.serial_label = QtWidgets.QLabel(CameraControlWidget)
        self.serial_label.setObjectName("serial_label")
        self.gridLayout.addWidget(self.serial_label, 5, 0, 1, 2)
        self.exposure_formLayout = QtWidgets.QFormLayout()
        self.exposure_formLayout.setObjectName("exposure_formLayout")
        self.exposure_label = QtWidgets.QLabel(CameraControlWidget)
        self.exposure_label.setMinimumSize(QtCore.QSize(150, 0))
        self.exposure_label.setObjectName("exposure_label")
        self.exposure_formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.exposure_label)
        self.exposure_lineEdit = QtWidgets.QLineEdit(CameraControlWidget)
        self.exposure_lineEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.exposure_lineEdit.setObjectName("exposure_lineEdit")
        self.exposure_formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.exposure_lineEdit)
        self.gridLayout.addLayout(self.exposure_formLayout, 4, 0, 1, 2)
        self.exposure_pushButton = QtWidgets.QPushButton(CameraControlWidget)
        self.exposure_pushButton.setEnabled(False)
        self.exposure_pushButton.setObjectName("exposure_pushButton")
        self.gridLayout.addWidget(self.exposure_pushButton, 8, 0, 1, 2)
        self.video_radioButton = QtWidgets.QRadioButton(CameraControlWidget)
        self.video_radioButton.setChecked(True)
        self.video_radioButton.setObjectName("video_radioButton")
        self.gridLayout.addWidget(self.video_radioButton, 10, 0, 1, 1)
        self.absorption_radioButton = QtWidgets.QRadioButton(CameraControlWidget)
        self.absorption_radioButton.setObjectName("absorption_radioButton")
        self.gridLayout.addWidget(self.absorption_radioButton, 10, 1, 1, 1)

        self.retranslateUi(CameraControlWidget)
        QtCore.QMetaObject.connectSlotsByName(CameraControlWidget)

    def retranslateUi(self, CameraControlWidget):
        _translate = QtCore.QCoreApplication.translate
        self.arm_pushButton.setText(_translate("CameraControlWidget", "Arm Camera"))
        self.start_pushButton.setText(_translate("CameraControlWidget", "Start Camera"))
        self.serial_label.setText(_translate("CameraControlWidget", "Serial Number: xxxxxxxx"))
        self.exposure_label.setText(_translate("CameraControlWidget", "Exposure Time (ms)"))
        self.exposure_lineEdit.setText(_translate("CameraControlWidget", "10"))
        self.exposure_pushButton.setText(_translate("CameraControlWidget", "Update Exposure Time"))
        self.video_radioButton.setText(_translate("CameraControlWidget", "Video"))
        self.absorption_radioButton.setText(_translate("CameraControlWidget", "Absorption"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CameraControlWidget = QtWidgets.QWidget()
    ui = Ui_CameraControlWidget()
    ui.setupUi(CameraControlWidget)
    CameraControlWidget.show()
    sys.exit(app.exec_())
