# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plothistorywidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PlotHistoryWidget(object):
    def setupUi(self, PlotHistoryWidget):
        PlotHistoryWidget.setObjectName("PlotHistoryWidget")
        PlotHistoryWidget.resize(613, 267)
        self.gridLayout = QtWidgets.QGridLayout(PlotHistoryWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.data_label = QtWidgets.QLabel(PlotHistoryWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.data_label.setFont(font)
        self.data_label.setObjectName("data_label")
        self.gridLayout.addWidget(self.data_label, 0, 0, 2, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 2, 1, 1)
        self.clear_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.gridLayout.addWidget(self.clear_pushButton, 3, 3, 1, 1)
        self.set_max_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.set_max_pushButton.setObjectName("set_max_pushButton")
        self.gridLayout.addWidget(self.set_max_pushButton, 3, 1, 1, 1)
        self.set_min_pushButton = QtWidgets.QPushButton(PlotHistoryWidget)
        self.set_min_pushButton.setObjectName("set_min_pushButton")
        self.gridLayout.addWidget(self.set_min_pushButton, 3, 0, 1, 1)
        self.bg_subtract_checkBox = QtWidgets.QCheckBox(PlotHistoryWidget)
        self.bg_subtract_checkBox.setObjectName("bg_subtract_checkBox")
        self.gridLayout.addWidget(self.bg_subtract_checkBox, 3, 4, 1, 1)
        self.history_PlotWidget = PlotWidget(PlotHistoryWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_PlotWidget.sizePolicy().hasHeightForWidth())
        self.history_PlotWidget.setSizePolicy(sizePolicy)
        self.history_PlotWidget.setObjectName("history_PlotWidget")
        self.gridLayout.addWidget(self.history_PlotWidget, 2, 0, 1, 5)
        self.linear_checkBox = QtWidgets.QCheckBox(PlotHistoryWidget)
        self.linear_checkBox.setObjectName("linear_checkBox")
        self.scale_mode_buttonGroup = QtWidgets.QButtonGroup(PlotHistoryWidget)
        self.scale_mode_buttonGroup.setObjectName("scale_mode_buttonGroup")
        self.scale_mode_buttonGroup.addButton(self.linear_checkBox)
        self.gridLayout.addWidget(self.linear_checkBox, 4, 0, 1, 1)
        self.log_checkBox = QtWidgets.QCheckBox(PlotHistoryWidget)
        self.log_checkBox.setObjectName("log_checkBox")
        self.scale_mode_buttonGroup.addButton(self.log_checkBox)
        self.gridLayout.addWidget(self.log_checkBox, 4, 1, 1, 1)

        self.retranslateUi(PlotHistoryWidget)
        QtCore.QMetaObject.connectSlotsByName(PlotHistoryWidget)

    def retranslateUi(self, PlotHistoryWidget):
        _translate = QtCore.QCoreApplication.translate
        PlotHistoryWidget.setWindowTitle(_translate("PlotHistoryWidget", "Plot History Window"))
        self.data_label.setText(_translate("PlotHistoryWidget", "0"))
        self.clear_pushButton.setText(_translate("PlotHistoryWidget", "Clear History"))
        self.set_max_pushButton.setText(_translate("PlotHistoryWidget", "Set Maximum"))
        self.set_min_pushButton.setText(_translate("PlotHistoryWidget", "Set Minimum"))
        self.bg_subtract_checkBox.setText(_translate("PlotHistoryWidget", "Background Subtract?"))
        self.linear_checkBox.setText(_translate("PlotHistoryWidget", "Linear"))
        self.log_checkBox.setText(_translate("PlotHistoryWidget", "Logarithmic"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PlotHistoryWidget = QtWidgets.QWidget()
    ui = Ui_PlotHistoryWidget()
    ui.setupUi(PlotHistoryWidget)
    PlotHistoryWidget.show()
    sys.exit(app.exec_())
