# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roianalyzer.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RoiAnalyzer(object):
    def setupUi(self, RoiAnalyzer):
        RoiAnalyzer.setObjectName("RoiAnalyzer")
        RoiAnalyzer.resize(195, 101)
        self.verticalLayout = QtWidgets.QVBoxLayout(RoiAnalyzer)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(RoiAnalyzer)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.enable_checkBox = QtWidgets.QCheckBox(RoiAnalyzer)
        self.enable_checkBox.setObjectName("enable_checkBox")
        self.verticalLayout.addWidget(self.enable_checkBox)
        self.bg_subtract_checkBox = QtWidgets.QCheckBox(RoiAnalyzer)
        self.bg_subtract_checkBox.setObjectName("bg_subtract_checkBox")
        self.verticalLayout.addWidget(self.bg_subtract_checkBox)

        self.retranslateUi(RoiAnalyzer)
        QtCore.QMetaObject.connectSlotsByName(RoiAnalyzer)

    def retranslateUi(self, RoiAnalyzer):
        _translate = QtCore.QCoreApplication.translate
        RoiAnalyzer.setWindowTitle(_translate("RoiAnalyzer", "Form"))
        self.label.setText(_translate("RoiAnalyzer", "ROI Analyzer"))
        self.enable_checkBox.setText(_translate("RoiAnalyzer", "Enable"))
        self.bg_subtract_checkBox.setText(_translate("RoiAnalyzer", "Background Subtract"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RoiAnalyzer = QtWidgets.QWidget()
    ui = Ui_RoiAnalyzer()
    ui.setupUi(RoiAnalyzer)
    RoiAnalyzer.show()
    sys.exit(app.exec_())
